#!/bin/bash -e

apt install -y openssh-server

read -p "ssh password login will be disabled, press enter to continue"

cat > /etc/ssh/sshd_config <<EOF
UsePAM yes
ChallengeResponseAuthentication no
PasswordAuthentication no
PrintMotd no
AcceptEnv LANG LC_*
KexAlgorithms diffie-hellman-group-exchange-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,curve25519-sha256,curve25519-sha256@libssh.org
MACs hmac-sha2-256,hmac-sha2-512,umac-128@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com
EOF

service ssh restart
