#!/bin/bash -e

apt install -y curl

# https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions-enterprise-linux-fedora-and-snap-packages
curl -sL https://deb.nodesource.com/setup_14.x | bash -
apt-get install -y nodejs

npm install -g pm2

adduser --gecos "" --disabled-password noderunner
