#!/bin/bash -e

apt install -y fp-compiler fp-units-fcl fp-units-net libc6-dev

WATTSI_DIR=/home/noderunner/wattsi

git clone https://github.com/whatwg/wattsi.git "$WATTSI_DIR"
chown -R noderunner:noderunner "$WATTSI_DIR"

cd "$WATTSI_DIR"
sudo --user noderunner ./build.sh
