#!/bin/bash -e

apt-get install apache2

a2enmod rewrite
a2enmod ssl
a2enmod headers

cp apache/conf/*.conf /etc/apache2/conf-available/
a2enconf http
a2enconf zz_local

chown -R deploy:deploy /var/www
rm -rf /var/www/html

apache2ctl configtest
apache2ctl restart
