#!/bin/bash -e

# a2dissite doesn't work if nothing is enabled
cp apache/*.org.conf /etc/apache2/sites-available/

for domain in `cat DOMAINS`; do
 a2ensite $domain || :
done

# TODO: set up initial deploy and auto deploy of sites.
# For books and figures, just git clone them.

service apache2 reload
