#!/bin/bash -e

# a2dissite doesn't work if nothing is enabled
cp apache/*.org.conf /etc/apache2/sites-available/

for domain in `cat DOMAINS`; do
 a2ensite $domain || :
done

apache2ctl configtest
apache2ctl restart
