#!/bin/bash -e

rm -f /etc/nginx/sites-enabled/*
cp nginx/sites/*.conf /etc/nginx/sites-available/

for domain in `cat DOMAINS`; do
    ln -s /etc/nginx/sites-available/$domain.conf /etc/nginx/sites-enabled/
done

nginx -t
systemctl reload-or-restart nginx.service
