#!/bin/bash -e

# build and install fdupes with --linkhard support (not in debian package)
apt install -y make gcc
git clone https://github.com/tobiasschulz/fdupes tmp
cd tmp
make install
cd ..
rm -rf tmp
apt remove -y make gcc
apt autoremove -y
