#!/bin/bash -e

rm -f /etc/nginx/sites-enabled/*
cp nginx/sites/*.conf /etc/nginx/sites-available/

for domain in `cat DOMAINS | tr , ' '`; do
    ln -s /etc/nginx/sites-available/$domain.conf /etc/nginx/sites-enabled/
done

/usr/sbin/nginx -t
systemctl restart nginx.service
