# https://www.digitalocean.com/docs/app-platform/references/app-specification-reference/
domains:
- domain: build.whatwg.org
  type: PRIMARY
  zone: whatwg.org
name: build
region: nyc
services:
- dockerfile_path: Dockerfile
  envs:
  - key: VERSION
    scope: RUN_TIME
    value: ${_self.COMMIT_HASH}
  github:
    branch: main
    deploy_on_push: true
    repo: whatwg/build.whatwg.org
  health_check:
    http_path: /version
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xs # basic-xss will not work; Wattsi requires more RAM
  name: build
  routes:
  - path: /
