#!/bin/bash -e

apt install -y curl

# https://github.com/nodesource/distributions#debinstall
curl -sL https://deb.nodesource.com/setup_14.x | bash -
apt install -y nodejs

npm install -g pm2

adduser --gecos "" --disabled-password noderunner
