name: Deploy
on:
  push:
    branches:
    - digitalocean-apps
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - run: ./digitalocean/deploy.sh
